### ISSUE TITLE
Links with target=_blank open outside Kolibri

### ISSUE THREAD

**Issue by dylanmccall** [learningequality/kolibri-installer-gnome#7]
Kolibri sometimes has links with target=_blank, such as in the "Coach" section before any classes have been created:

![Screenshot from 2020-08-12 15-50-21](https://user-images.githubusercontent.com/132063/90076019-9711bc00-dcb3-11ea-9766-2e5883339d2d.png)

Clicking one of these links in the app opens the default web browser. Instead, links like these (internal links which don't look like file downloads) should always open in the app, in the current window.

**Comment by indirectlylit** [comment]
Note that this particular behavior is actually a regression - opened a new issue here: https://github.com/learningequality/kolibri/issues/7480

After that regression is fixed, we may need to revert #8 because there will actually be other scenarios where `_blank` links _are_ intended to open in an external web browser, for example:

![2020-08-17 17 50 41](https://user-images.githubusercontent.com/2367265/90458129-58647300-e0b2-11ea-9078-178118d5d492.gif)
